[package]
name = "ht-time-sheet"
version = "0.1.0"
authors = ["Martin Thurau <martin.thurau@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.11"
serde = { version = "1.0.116", features = ["derive"] }
csv = "1.1"
anyhow = "1.0.42"
chrono = "0.4.19"
hhmmss = "0.1.0"
